### ISSUE TITLE
Can't see menubar icon

### ISSUE THREAD

**Issue by tkosman-idt** [ThatNerdSquared/timers-for-raycast#12] opened 2023-12-07 11:44 UTC
MacOS Sonoma 14.1.2 (23B92)
I selected in Show Menu Bar Item When both Always and When Running. But nothing happens.

**Comment by tkosman-idt** [comment] 2023-12-10 09:15
Thanks.
I didn't run this "Timers Menu Bar" command. But when I ran it – nothing changed.
I just installed that extension and didn't know how it should work.
I stopped to do things on 2 days (my weekend)
When I came back – everything was OK.

Conclusion: The problem has been solved. But I don't understand how.

**Comment by ThatNerdSquared** [comment] 2023-12-10 23:43
Hm, that's weird. Did you run any timers between the time it didn't work and the time it did?

The menu bar item only refreshes every 10 seconds or so, and it can get killed off by the system sometimes, so perhaps that was why it started working after a while? Not sure.

**Comment by ThatNerdSquared** [comment] 2023-12-11 20:43
Ahh, that is probably it, then. I should add that to the list of debugging questions.

I'm closing this issue now since it seems like the problem is resolved - feel free to reopen if it comes back though. Thanks for using Timers :)

**Closed by ThatNerdSquared** 2023-12-11 20:43 UTC
